### ISSUE TITLE
Brackets in values, kill parsing

### ISSUE THREAD

**Issue by JayWood** [janeklb/JSONCharInputReader#3]
Ran into this today, no fix as of yet, but we have a json feed which has occasionally brackets inside of the data sets.

Example
`[
  {
    "cLabel": "$69} for Carpet Cleaning for Three Rooms ($405 Value)."
  },
  {
    "cLabel": "This is a good label"
  }
]`

The first cLabel will think it's closed after `$69}` and not return a valid json object.  I only ran into this with the curly brace, I would assume square brackets have the same issue looking at the `STATE_INSQUARE` condition in `JSONCharInputReader::readChar()`

I would think we can check if we're in a string when we're also checking for brackets?

**Comment by janeklb** [comment]
Thanks for raising the issue - this is definitely a huge shortcoming of the parser. I'll have a look at it asap

**Comment by janeklb** [comment]
Fixed in 0.3.2!

**Comment by jtsternberg** [comment]
Thank you @janeklb!

**Comment by JayWood** [comment]
Thank you so much @janeklb you've saved me!
